name: galeria
description: "Um app para visualizar imagens e videos"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de mídia
  photo_manager: ^3.6.4
  photo_view: ^0.15.0
  video_player: ^2.9.3
  chewie: ^1.11.0
  subtitle: ^0.1.4

  # Permissões
  permission_handler: ^11.4.0
  receive_sharing_intent: ^1.8.1

  # Gerenciamento de arquivos e armazenamento
  file_picker: ^9.2.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  flutter_cache_manager: ^3.4.1
  extended_image: ^10.0.0

  # Edição de mídia
  pro_image_editor: ^9.1.0
  video_editor: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3

  # UI e Widgets
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.4
  hugeicons: ^0.0.10

  # Compartilhamento
  share_plus: ^10.1.4

  # Utilitários
  watcher: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700